// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Web_Estoque_E_Faturamento.MvcIndependentObjectsOfProductsContextSqlServer
{
    [DbContext(typeof(MvcIndependentObjectsOfProductsContext))]
    [Migration("20220827012424_NewMigrationsModels")]
    partial class NewMigrationsModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web_Estoque_E_Faturamento._Models.ProductListReminderToBuyWithoutUseProductAlreadyRegistered", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AlreadyBuyed")
                        .HasColumnType("bit");

                    b.Property<string>("CodeOfProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfCreation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("QuantityToBuy")
                        .HasColumnType("real");

                    b.Property<bool>("WillBePurchased")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ProductListReminderToBuyWithoutUseProductAlreadyRegistered");
                });
#pragma warning restore 612, 618
        }
    }
}
